### ISSUE TITLE
Errors - new install on Lucid

### ISSUE THREAD

**Issue by david-rahrer** [toddself/Medieer#1]
I've only just started trying to use Medieer and I'm hoping to make use of it.  I installed v.65 on Lucid and I'm getting the following errors when trying to see the settings using the -s flag:

Traceback (most recent call last):
  File "/usr/local/bin/Medieer.py", line 5, in <module>
    pkg_resources.run_script('Medieer==0.65', 'Medieer.py')
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 461, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 1194, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.6/dist-packages/Medieer-0.65-py2.6.egg/EGG-INFO/scripts/Medieer.py", line 648, in <module>
    mi = Medieer(sys.argv[1:])
  File "/usr/local/lib/python2.6/dist-packages/Medieer-0.65-py2.6.egg/EGG-INFO/scripts/Medieer.py", line 88, in **init**
    self.show_defaults()
  File "/usr/local/lib/python2.6/dist-packages/Medieer-0.65-py2.6.egg/EGG-INFO/scripts/Medieer.py", line 201, in show_defaults
    value_width = max([len(setting.value) for setting in settings])
ValueError: max() arg is an empty sequence

The required modules are installed.  I have some other questions but I'll use separate issues for that.  Thanks.

**Comment by toddself** [comment]
can you add --debug DEBUG to the command line and post the last 15 lines of ~/.config/medieer/Medieer.log?

I'll try to replicate.  Also to confirm you're using python 2.6?

Thanks!

(Sorry for the tardy delay - it was vacation last week!)

**Comment by david-rahrer** [comment]
Hi,

Python 2.6.5

Adding the debug flag yields nothing in the log, it's empty.  I should
mention that I've not found any actual usage instructions for Medieer, so I
may not be doing anything correctly.  Do you have a tutorial or instruction
file somewhere?

The error I mentioned comes from just trying to view the existing settings,
i.e. "Medieer.py -s" and I tried putting the debug flag on the end of that
as requested, but nothing goes to the log.  Any instructions on how to
actually set up and use this might help track the error down or eliminate
it.

I'm really hoping to be able to use Medieer, it will fit my plans for Roku
box beautifully.

David Rahrer
